version: "3.7"
services: 
    #Imagem laravel app packages
    laravel_packages:
        build: 
            args: 
                user: micro_01      #Will be used in Dockerfile
                uid: 1000           #Will be used in Dockerfile
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        #command: "php artisan serve"   #This could be done but is not a good practice
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - packages

    #nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8003:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d     #if using apache ./docker/apache:/etc/apache2/sites-available/, create the conf file
        networks:
            - packages

    #mysql
    db_laravel_packages:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/db_data:/var/lib/mysql      #Database will be saved in this folder... DON'T FORGET to add it in .gitignore
        networks:
            - packages
    
networks:
    packages:
        driver: bridge    

        